export const trainingRequestButton = ':nth-child(1) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const acceptedRequestButton = ':nth-child(2) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const trainersButton=':nth-child(3) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const currentTraineesButtonForCompany = 'nth-child(4) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const completedTraineesButton = 'nth-child(5) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const editTrainingButton = 'nth-child(6) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root';
export const archiveButton = 'nth-child(7) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const companyButtons = [trainingRequestButton,acceptedRequestButton,trainersButton,currentTraineesButtonForCompany,completedTraineesButton,editTrainingButton];
export const requestsButton =':nth-child(1) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const submittedTraineesButton = ':nth-child(2) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const companiesButton = ':nth-child(3) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const currentTraineesButtonForUniversity = ':nth-child(4) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const completedTraineesButtonForUniversity = ':nth-child(5) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const archiveButtonForUniversity = ':nth-child(6) > .MuiStack-root > .MuiAvatar-root > .MuiButtonBase-root'
export const universityButtons=[requestsButton,submittedTraineesButton,companiesButton,currentTraineesButtonForUniversity,completedTraineesButtonForUniversity,archiveButtonForUniversity]